### ISSUE TITLE
Install not working on Mac OSX ?

### ISSUE THREAD

**Issue by tarilabs** [mvndaemon/homebrew-mvnd#3]
It would appear like after #2 , it broke Mac OSX installs? (thanks @lucamolteni for the ref to this repo)

Following this instructions: https://github.com/mvndaemon/mvnd#install-using-homebrew
I get:
```
$ brew install mvndaemon/homebrew-mvnd/mvnd
Updating Homebrew...
==> Tapping mvndaemon/mvnd
Cloning into '/usr/local/Homebrew/Library/Taps/mvndaemon/homebrew-mvnd'...
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 70 (delta 28), reused 57 (delta 17), pack-reused 0
Unpacking objects: 100% (70/70), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/mvndaemon/homebrew-mvnd/Formula/mvnd.rb
formulae require at least a URL
Error: Cannot tap mvndaemon/mvnd: invalid syntax in tap!
```

![Screenshot 2020-12-16 at 13 38 39](https://user-images.githubusercontent.com/1699252/102356345-61584900-3fad-11eb-9296-5e0f46a6a838.png)

which looks somehow caused by?

https://github.com/mvndaemon/homebrew-mvnd/commit/c71eb13ae62ad372344bbdd5a9e15f4edf5eb54e#diff-8cd17450ac232e461b1c809c078c8516f21f02506b2d77d8a20ea24ef69cbecbL4

This is my system information:

```
$ brew --version
Homebrew 2.6.2
Homebrew/homebrew-core (git revision 377d7b; last commit 2020-12-16)
Homebrew/homebrew-cask (git revision 19365; last commit 2020-12-16)
```

**Comment by gnodet** [comment]
It should be fixed by https://github.com/mvndaemon/homebrew-mvnd/commit/22a9c854943a5b2b143e94c123f094ad6f2427e6

**Comment by tarilabs** [comment]
Thank you @gnodet !
